### ISSUE TITLE
Checklist - BT tuần 9

### ISSUE THREAD

**Issue by longlyduc** [longld12020236/kt_Group23#1]
Phân loại:
-phần nhập dữ liệu.
-phần xử lý dữ liệu.

Loại hình kiểm tra:
Nhìn mã nguồn, tìm bug và sửa bug.

Danh sách các tính năng:
tính tuổi chính xác đến tháng dựa vào thời gian hiện tại và năm, tháng sinh.

Danh sách các mục cần kiểm tra đối với tính năng trên:
-tính tuổi chỉ theo năm.
-tính tuổi theo năm và tháng.

Các lỗi chính cần check:
1. Dùng biến chưa có giá trị xác định ?
2. Dùng chỉ số của biến array nằm ngoài phạm vi ? 
3. Dùng chỉ số không thuộc kiểu nguyên của biến array ?
4. Tham khảo đến dữ liệu không tồn tại ?
5. Tất cả các biến đều được định nghĩa hay khai báo tường
   minh chưa?
6. Định nghĩa hay khai báo đầy đủ các thuộc tính của biến dữ
   liệu chưa?
7. Có dùng các biến ý nghĩa khác nhau nhưng tên rất giống
   nhau không?
8. Thực hiện phép toán trên toán hạng không phải là số?
9. Thực hiện phép toán trên các toán hạng có kiểu không
   tương thích ?
10. Thực hiện phép toán trên các toán hạng có độ dài khác
    nhau ?
11. Phép chia có mẫu bằng 0 ?
12. Giá trị biến nằm ngoài phạm vi ngữ nghĩa ?
13. Thứ tự thực hiện các phép toán trong biểu thức mà người
    lập trình mong muốn có tương thích với thứ tự mà máy
    thực hiện? Người lập trình hiểu ₫úng về thứ tự ưu tiên các
    phép toán chưa ?
14. Kết quả phép chia nguyên có chính xác theo yêu cầu
    không ?
15. So sánh 2 dữ liệu có kiểu không tương thích ?
16. So sánh 2 dữ liệu có kiểu không cùng độ dài ?
17. Toán tử so sánh đúng ngữ nghĩa mong muốn? Dễ lộn giữa
    = và ≠, <= và >=, and và or...
18. Có nhầm lẫn giữa biểu thức Bool và biểu thức so sánh ?
19. Có hiễu rõ thứ tự ưu tiên các phép toán ? 
    if(a==2 && b==2 || c==3) {...}
20. Có đủ và đúng cặp token begin/end, {} ?
21. thứ tự các tham số có đúng không ?
22. Chuỗi xuất có bị lỗi từ vựng và cú pháp không ?
23. Có các cảnh báo hay thông báo thông tin ?
24. Có kiểm tra tính xác thực của dữ liệu nhập chưa ?

**Comment by musashi19xx** [comment]
1. [x] Dùng biến chưa có giá trị xác định ?
2. [x] Dùng chỉ số của biến array nằm ngoài phạm vi ?
3. [x] Dùng chỉ số không thuộc kiểu nguyên của biến array ?
4. [x] Tham khảo đến dữ liệu không tồn tại ?
5. [x] Tất cả các biến đều được định nghĩa hay khai báo tường
   minh chưa?
6. [x] Định nghĩa hay khai báo đầy đủ các thuộc tính của biến dữ
   liệu chưa?
7. [x] Có dùng các biến ý nghĩa khác nhau nhưng tên rất giống
   nhau không?
8. [x] Thực hiện phép toán trên toán hạng không phải là số?
9. [x] Thực hiện phép toán trên các toán hạng có kiểu không
   tương thích ?
10. [x] Thực hiện phép toán trên các toán hạng có độ dài khác
    nhau ?
11. [x] Phép chia có mẫu bằng 0 ?
12. [x] Giá trị biến nằm ngoài phạm vi ngữ nghĩa ?
13. [x] Thứ tự thực hiện các phép toán trong biểu thức mà người
    lập trình mong muốn có tương thích với thứ tự mà máy
    thực hiện? Người lập trình hiểu đúng về thứ tự ưu tiên các
    phép toán chưa ?
14. [x] Kết quả phép chia nguyên có chính xác theo yêu cầu
    không ?
15. [x] So sánh 2 dữ liệu có kiểu không tương thích ?
16. [x] So sánh 2 dữ liệu có kiểu không cùng độ dài ?
17. [x] Toán tử so sánh đúng ngữ nghĩa mong muốn? Dễ lộn giữa
    = và ≠, <= và >=, and và or...
18. [x] Có nhầm lẫn giữa biểu thức Bool và biểu thức so sánh ?
19. [x] Có hiễu rõ thứ tự ưu tiên các phép toán ? 
    if(a==2 && b==2 || c==3) {...}
20. [x] Có đủ và đúng cặp token begin/end, {} ?
21. [x] thứ tự các tham số có đúng không ?
22. [x] Chuỗi xuất có bị lỗi từ vựng và cú pháp không ?
23. [ ] Có các cảnh báo hay thông báo thông tin ?
24. [ ] Có kiểm tra tính xác thực của dữ liệu nhập chưa ?
